# Generated by Django 2.2.5 on 2019-10-02 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=50)),
                ('fk_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Employee')),
            ],
        ),
    ]
